// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5csbN3A1zFAr2TIrZmfTlZsdo7FfFMA0',
    appId: '1:464970622160:android:2494f61eb733c2a0f06ad5',
    messagingSenderId: '464970622160',
    projectId: 'fir-76c7d',
    databaseURL: 'https://fir-76c7d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-76c7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-OKLO1MaEtOivkWq5GYcsONF1rr0i65o',
    appId: '1:464970622160:ios:5622d906a424768cf06ad5',
    messagingSenderId: '464970622160',
    projectId: 'fir-76c7d',
    databaseURL: 'https://fir-76c7d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-76c7d.appspot.com',
    iosClientId: '464970622160-6sebu6f5pg3rbrpbmb81n2cgimrmcff3.apps.googleusercontent.com',
    iosBundleId: 'com.dhiwise.budget.tracking',
  );
}
